base_url: https://urednik-digital-kvpz.vercel.app/
repo: https://github.com/cesko-digital/urednik.digital
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'events'
    label: 'Eventy'
    folder: '_events/'
    create: true
    fields:
      - { name: title }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: Image, name: image, widget: image}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'To mě zajímá', name: has_button, widget: boolean }
      - { labe: 'To mě zajímá url', name: button_link, widget: url }
  - name: 'done_events'
    label: 'Záznamy'
    folder: '_done_events/'
    create: true
    fields:
      - { name: title }
      - { label: Image, name: image, widget: image}
      - { label: 'Link', name: 'more_url', widget: 'string' }
      - { label: 'Annotation', name: 'annotation', widget: 'text' }
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    fields:
      - { name: title }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Anototation", name: anotation, widget: string }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'O nás'
        name: 'about'
        file: 'about.markdown'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - label: Contacts
            name: contacts
            widget: list
            fields:
              - label: Text
                name: name
                widget: string
              - label: Link
                name: link
                widget: string
              - label: Icon
                name: icon
                widget: string
          - label: "Kontakty text"
            name: contactsText
            widget: string
          - label: "Proč to děláme?"
            name: why
            widget: string
          - label: "Co děláme?"
            name: what
            widget: string
          - label: "Zapojte se"
            name: join
            widget: markdown
          - label: Team
            name: team
            widget: list
            fields:
              - label: Oblast
                name: name
                widget: string
              - label: Členové
                name: members
                widget: list
                fields:
                  - label: Jméno
                    name: name
                    widget: string
                  - label: Fotka
                    name: image
                    widget: image
                  - label: Funkce
                    name: function
                    widget: string
          - label: Behind
            name: behind
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Logo
                name: logo
                widget: image
              - label: Points
                name: points
                widget: list
                fields:
                  - label: Point
                    name: point
                    widget: string
      - label: Metodika
        name: metodika
        file: metodika.md
        fields:
          - label: Ke stažení
            name: files
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: File
                name: url
                widget: file
          - label: Blocks
            name: blocks
            widget: list
            fields:
              - label: Blok
                name: block
                widget: markdown
      - label: Home
        name: home
        file: index.markdown
        fields:
          - label: Titulek
            name: h1
            widget: string
          - label: Perex
            name: perex
            widget: string
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Footer'
        name: 'footer'
        file: '_data/footer.yml'
        fields:
          - label: 'Contacts'
            name: 'contacts'
            widget: 'list'
            # fields:
            #   - { label: Name, name: name, widget: string }
            #   - { label: Link, name: link, widget: string }
          - label: "Main text"
            name: main
            widget: string
          - label: "Secondary text"
            name: secondary
            widget: string
          - label: "Cookies text"
            name: cookies
            widget: string
          - label: "Copyright text"
            name: copyright
            widget: string
          - label: 'Social'
            name: 'social'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
              - { label: Icon, name: icon, widget: string }